// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OOPAlgoQuizGame.Data;

#nullable disable

namespace OOPAlgoQuizGame.Migrations
{
    [DbContext(typeof(QuizDbContext))]
    [Migration("20260411162259_init233")]
    partial class init233
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OOPAlgoQuizGame.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Explanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "SP",
                            CorrectAnswer = "C",
                            Explanation = "for/while loops — This is the correct answer. In C++, this concept applies as described.",
                            OptionA = "if-else",
                            OptionB = "switch",
                            OptionC = "for/while loops",
                            OptionD = "try-catch",
                            QuestionText = "Which control structure is primarily used for repetition in structured programming?"
                        },
                        new
                        {
                            Id = 2,
                            Category = "SP",
                            CorrectAnswer = "B",
                            Explanation = "Sequential, selection, iteration — This is the correct answer. In C++, this concept applies as described.",
                            OptionA = "GOTO-based flow",
                            OptionB = "Sequential, selection, iteration",
                            OptionC = "Spaghetti code",
                            OptionD = "Self-modifying code",
                            QuestionText = "Structured programming emphasizes which of the following?"
                        },
                        new
                        {
                            Id = 3,
                            Category = "SP",
                            CorrectAnswer = "D",
                            Explanation = "if-else — This is the correct answer. In C++, this concept applies as described.",
                            OptionA = "for loop",
                            OptionB = "while loop",
                            OptionC = "switch",
                            OptionD = "if-else",
                            QuestionText = "In C++, which construct is a structured way to select between two alternatives?"
                        },
                        new
                        {
                            Id = 4,
                            Category = "SP",
                            CorrectAnswer = "B",
                            Explanation = "Functions and procedures — This is the correct answer. In C++, this concept applies as described.",
                            OptionA = "Global variables only",
                            OptionB = "Functions and procedures",
                            OptionC = "GOTO statements",
                            OptionD = "Inline assembly",
                            QuestionText = "Which C++ feature helps break a program into reusable pieces (structured approach)?"
                        },
                        new
                        {
                            Id = 5,
                            Category = "SP",
                            CorrectAnswer = "B",
                            Explanation = "for / while loops — This is the correct answer. In C++, this concept applies as described.",
                            OptionA = "Recursion only",
                            OptionB = "for / while loops",
                            OptionC = "Unstructured jumps",
                            OptionD = "Macros",
                            QuestionText = "What is the preferred way to handle iteration in structured programming (C++)?"
                        },
                        new
                        {
                            Id = 6,
                            Category = "SP",
                            CorrectAnswer = "C",
                            Explanation = "It creates spaghetti code — This is the correct answer. In C++, this concept applies as described.",
                            OptionA = "It improves readability",
                            OptionB = "It causes predictable flow",
                            OptionC = "It creates spaghetti code",
                            OptionD = "It removes loops",
                            QuestionText = "Why avoid GOTO in structured programming?"
                        },
                        new
                        {
                            Id = 7,
                            Category = "SP",
                            CorrectAnswer = "B",
                            Explanation = "Begin with high-level modules — This is the correct answer. In C++, this concept applies as described.",
                            OptionA = "Start with low-level code",
                            OptionB = "Begin with high-level modules",
                            OptionC = "Write random functions",
                            OptionD = "Mix UI and logic",
                            QuestionText = "Which is a top-down structured design practice?"
                        },
                        new
                        {
                            Id = 8,
                            Category = "SP",
                            CorrectAnswer = "B",
                            Explanation = "Small focused functions — This is the correct answer. In C++, this concept applies as described.",
                            OptionA = "Large monolithic functions",
                            OptionB = "Small focused functions",
                            OptionC = "One-file programs",
                            OptionD = "Multiple global flags",
                            QuestionText = "In C++ structured programs, which promotes maintainability?"
                        },
                        new
                        {
                            Id = 9,
                            Category = "SP",
                            CorrectAnswer = "B",
                            Explanation = "Clear, linear control flow — This is the correct answer. In C++, this concept applies as described.",
                            OptionA = "Reduce modularity",
                            OptionB = "Clear, linear control flow",
                            OptionC = "Increase GOTO usage",
                            OptionD = "Maximize side effects",
                            QuestionText = "Which statement best expresses structured programming goal?"
                        },
                        new
                        {
                            Id = 10,
                            Category = "SP",
                            CorrectAnswer = "B",
                            Explanation = "for/while with clear exit — This is the correct answer. In C++, this concept applies as described.",
                            OptionA = "Unbounded GOTO",
                            OptionB = "for/while with clear exit",
                            OptionC = "Nested gotos",
                            OptionD = "Self-modifying loops",
                            QuestionText = "Which construct should you prefer for clarity in C++ loops?"
                        },
                        new
                        {
                            Id = 11,
                            Category = "SOLID",
                            CorrectAnswer = "B",
                            Explanation = "Single responsibility, Open/closed, Liskov substitution, Interface segregation, Dependency inversion — This is the correct answer. In Design principles (language agnostic), this concept applies as described.",
                            OptionA = "System Object Logic Interface Design",
                            OptionB = "Single responsibility, Open/closed, Liskov substitution, Interface segregation, Dependency inversion",
                            OptionC = "Simple Object Language Interface Definition",
                            OptionD = "Strong Object Linking Interface Design",
                            QuestionText = "What does SOLID stand for?"
                        },
                        new
                        {
                            Id = 12,
                            Category = "SOLID",
                            CorrectAnswer = "B",
                            Explanation = "Each class has one reason to change — This is the correct answer. In Design principles (language agnostic), this concept applies as described.",
                            OptionA = "One class many reasons to change",
                            OptionB = "Each class has one reason to change",
                            OptionC = "Multiple responsibilities encouraged",
                            OptionD = "No responsibilities",
                            QuestionText = "Single Responsibility Principle means?"
                        },
                        new
                        {
                            Id = 13,
                            Category = "SOLID",
                            CorrectAnswer = "B",
                            Explanation = "Open for extension, closed for modification — This is the correct answer. In Design principles (language agnostic), this concept applies as described.",
                            OptionA = "Open for modification only",
                            OptionB = "Open for extension, closed for modification",
                            OptionC = "Closed for both",
                            OptionD = "Always modifying code",
                            QuestionText = "Open/Closed Principle is about?"
                        },
                        new
                        {
                            Id = 14,
                            Category = "SOLID",
                            CorrectAnswer = "B",
                            Explanation = "Depend on abstractions, not implementations — This is the correct answer. In Design principles (language agnostic), this concept applies as described.",
                            OptionA = "Depend on concrete classes",
                            OptionB = "Depend on abstractions, not implementations",
                            OptionC = "Invert class hierarchy",
                            OptionD = "No dependencies",
                            QuestionText = "Dependency Inversion means?"
                        },
                        new
                        {
                            Id = 15,
                            Category = "SOLID",
                            CorrectAnswer = "B",
                            Explanation = "Small specific interfaces — This is the correct answer. In Design principles (language agnostic), this concept applies as described.",
                            OptionA = "Large interfaces",
                            OptionB = "Small specific interfaces",
                            OptionC = "No interfaces",
                            OptionD = "Multiple inheritance",
                            QuestionText = "Interface Segregation advocates?"
                        },
                        new
                        {
                            Id = 16,
                            Category = "OOP",
                            CorrectAnswer = "B",
                            Explanation = "Encapsulation — This matches the core OOP concept. In Java, this is typically implemented using classes and interfaces.",
                            OptionA = "Inheritance",
                            OptionB = "Encapsulation",
                            OptionC = "Polymorphism",
                            OptionD = "Abstraction",
                            QuestionText = "Which principle focuses on bundling data and methods?"
                        },
                        new
                        {
                            Id = 17,
                            Category = "OOP",
                            CorrectAnswer = "B",
                            Explanation = "Redefining parent method in child — This matches the core OOP concept. In Java, this is typically implemented using classes and interfaces.",
                            OptionA = "Same method name, different signatures",
                            OptionB = "Redefining parent method in child",
                            OptionC = "Changing method return type",
                            OptionD = "Creating multiple methods",
                            QuestionText = "What is method overriding?"
                        },
                        new
                        {
                            Id = 18,
                            Category = "OOP",
                            CorrectAnswer = "C",
                            Explanation = "sealed — This matches the core OOP concept. In Java, this is typically implemented using classes and interfaces.",
                            OptionA = "abstract",
                            OptionB = "static",
                            OptionC = "sealed",
                            OptionD = "readonly",
                            QuestionText = "Which keyword prevents inheritance in C# or Java-like languages?"
                        },
                        new
                        {
                            Id = 19,
                            Category = "OOP",
                            CorrectAnswer = "B",
                            Explanation = "Same interface, different behavior — This matches the core OOP concept. In Java, this is typically implemented using classes and interfaces.",
                            OptionA = "Multiple data types",
                            OptionB = "Same interface, different behavior",
                            OptionC = "Data hiding",
                            OptionD = "Code reusability",
                            QuestionText = "What is polymorphism?"
                        },
                        new
                        {
                            Id = 20,
                            Category = "OOP",
                            CorrectAnswer = "B",
                            Explanation = "Hiding complexity — This matches the core OOP concept. In Java, this is typically implemented using classes and interfaces.",
                            OptionA = "Creating instances",
                            OptionB = "Hiding complexity",
                            OptionC = "Binding data",
                            OptionD = "Inheriting classes",
                            QuestionText = "What is abstraction?"
                        },
                        new
                        {
                            Id = 21,
                            Category = "DS",
                            CorrectAnswer = "B",
                            Explanation = "Stack — In C++ implementations, this property is used when implementing this data structure/algorithm.",
                            OptionA = "Queue",
                            OptionB = "Stack",
                            OptionC = "Heap",
                            OptionD = "Tree",
                            QuestionText = "LIFO principle followed by?"
                        },
                        new
                        {
                            Id = 22,
                            Category = "DS",
                            CorrectAnswer = "B",
                            Explanation = "Queue — In C++ implementations, this property is used when implementing this data structure/algorithm.",
                            OptionA = "Stack",
                            OptionB = "Queue",
                            OptionC = "Both",
                            OptionD = "Neither",
                            QuestionText = "FIFO principle followed by?"
                        },
                        new
                        {
                            Id = 23,
                            Category = "DS",
                            CorrectAnswer = "C",
                            Explanation = "O(1) — In C++ implementations, this property is used when implementing this data structure/algorithm.",
                            OptionA = "O(n)",
                            OptionB = "O(log n)",
                            OptionC = "O(1)",
                            OptionD = "O(n^2)",
                            QuestionText = "Array access time complexity?"
                        },
                        new
                        {
                            Id = 24,
                            Category = "DS",
                            CorrectAnswer = "B",
                            Explanation = "Left < Right — In C++ implementations, this property is used when implementing this data structure/algorithm.",
                            OptionA = "Left > Right",
                            OptionB = "Left < Right",
                            OptionC = "No order",
                            OptionD = "Random order",
                            QuestionText = "Binary Search Tree property?"
                        },
                        new
                        {
                            Id = 25,
                            Category = "DS",
                            CorrectAnswer = "C",
                            Explanation = "O(n log n) — In C++ implementations, this property is used when implementing this data structure/algorithm.",
                            OptionA = "O(n)",
                            OptionB = "O(log n)",
                            OptionC = "O(n log n)",
                            OptionD = "O(n^2)",
                            QuestionText = "Heap sort time complexity?"
                        },
                        new
                        {
                            Id = 26,
                            Category = ".NET",
                            CorrectAnswer = "A",
                            Explanation = "Common Language Runtime — In C#, this is how the framework or language behaves.",
                            OptionA = "Common Language Runtime",
                            OptionB = "Code Level Reuse",
                            OptionC = "C# Library Runtime",
                            OptionD = "Common Logic Run",
                            QuestionText = "CLR stands for?"
                        },
                        new
                        {
                            Id = 27,
                            Category = ".NET",
                            CorrectAnswer = "B",
                            Explanation = "JIT compiler — In C#, this is how the framework or language behaves.",
                            OptionA = "Direct CPU",
                            OptionB = "JIT compiler",
                            OptionC = "Interpreter",
                            OptionD = "Native code",
                            QuestionText = "IL code executes via?"
                        },
                        new
                        {
                            Id = 28,
                            Category = ".NET",
                            CorrectAnswer = "A",
                            Explanation = "Task — In C#, this is how the framework or language behaves.",
                            OptionA = "Task",
                            OptionB = "Promise",
                            OptionC = "Future",
                            OptionD = "Coroutine",
                            QuestionText = "async/await returns?"
                        },
                        new
                        {
                            Id = 29,
                            Category = ".NET",
                            CorrectAnswer = "B",
                            Explanation = "ORM session — In C#, this is how the framework or language behaves.",
                            OptionA = "Database table",
                            OptionB = "ORM session",
                            OptionC = "SQL connection",
                            OptionD = "DbSet",
                            QuestionText = "DbContext represents?"
                        },
                        new
                        {
                            Id = 30,
                            Category = ".NET",
                            CorrectAnswer = "A",
                            Explanation = "Migration file — In C#, this is how the framework or language behaves.",
                            OptionA = "Migration file",
                            OptionB = "Database",
                            OptionC = "Table",
                            OptionD = "Connection",
                            QuestionText = "Add-Migration creates?"
                        });
                });

            modelBuilder.Entity("OOPAlgoQuizGame.Models.Winner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAchieved")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Score")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Winners");
                });
#pragma warning restore 612, 618
        }
    }
}
