using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace OOPAlgoQuizGame.Migrations
{
    /// <inheritdoc />
    public partial class InitialCreate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Questions",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    QuestionText = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    OptionA = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    OptionB = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    OptionC = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    OptionD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    CorrectAnswer = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Category = table.Column<string>(type: "nvarchar(max)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Questions", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Winners",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Name = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Email = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Score = table.Column<double>(type: "float", nullable: false),
                    Category = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    DateAchieved = table.Column<DateTime>(type: "datetime2", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Winners", x => x.Id);
                });

            migrationBuilder.InsertData(
                table: "Questions",
                columns: new[] { "Id", "Category", "CorrectAnswer", "OptionA", "OptionB", "OptionC", "OptionD", "QuestionText" },
                values: new object[,]
                {
                    { 1, "SP", "B", "System Object Logic Interface Design", "Single responsibility, Open/closed, Liskov substitution, Interface segregation, Dependency inversion", "Simple Object Language Interface Definition", "Strong Object Linking Interface Design", "What does SOLID stand for?" },
                    { 2, "SP", "B", "One class many reasons to change", "Each class has one reason to change", "Multiple responsibilities encouraged", "No responsibilities", "Single Responsibility Principle means?" },
                    { 3, "SP", "B", "Liskov", "Open/Closed", "Interface Segregation", "Dependency Inversion", "Which principle forbids modification after release?" },
                    { 4, "SP", "B", "Open for modification only", "Open for extension, closed for modification", "Closed for both", "Always modifying code", "Open/Closed Principle is about?" },
                    { 5, "SP", "A", "Replace child with parent safely", "Replace parent with child safely", "No substitution allowed", "Random substitution", "What is Liskov Substitution Principle?" },
                    { 6, "SP", "B", "Large interfaces", "Small specific interfaces", "No interfaces", "Multiple inheritance", "Interface Segregation advocates?" },
                    { 7, "SP", "B", "Depend on concrete classes", "Depend on abstractions, not implementations", "Invert class hierarchy", "No dependencies", "Dependency Inversion means?" },
                    { 8, "SP", "B", "Class handling one concern", "Class handling UI, DB, and business logic", "Well-organized class", "Simple class", "SRP violation example?" },
                    { 9, "SP", "B", "Add more methods", "Split into multiple classes", "Merge classes", "Use inheritance", "How to fix SRP violation?" },
                    { 10, "SP", "B", "Direct modification", "Inheritance and composition", "Copy-paste code", "Global variables", "OCP achieved through?" },
                    { 11, "SP", "A", "OCP", "SRP", "DIP", "ISP", "Factory pattern relates to?" },
                    { 12, "SP", "A", "OCP", "SRP", "LSP", "DIP", "Strategy pattern relates to?" },
                    { 13, "SP", "A", "OCP", "SRP", "LSP", "ISP", "Decorator pattern supports?" },
                    { 14, "SP", "A", "OCP", "SRP", "ISP", "DIP", "Template Method pattern supports?" },
                    { 15, "SP", "B", "Child extends parent properly", "Child breaks parent contract", "Parent class design", "Interface implementation", "What violates LSP?" },
                    { 16, "SP", "C", "SRP", "OCP", "LSP", "ISP", "Rectangle and Square violates?" },
                    { 17, "SP", "B", "One large interface", "Multiple small interfaces", "No interfaces", "Abstract classes only", "ISP example?" },
                    { 18, "SP", "A", "Clients depend on unneeded methods", "Small interfaces", "Lean interfaces", "Required methods", "Fat interface problem?" },
                    { 19, "SP", "B", "Merge interfaces", "Split into role-based interfaces", "Enlarge interface", "Remove methods", "How to fix ISP?" },
                    { 20, "SP", "B", "Modules depend on details", "Modules depend on abstractions", "No modules", "Hard dependencies", "DIP core idea?" },
                    { 21, "SP", "B", "Direct object creation", "Framework controls flow", "No control", "User controls framework", "Inversion of Control (IoC)?" },
                    { 22, "SP", "B", "Constructor only", "Constructor, Property, Method", "Method only", "No types", "Dependency Injection types?" },
                    { 23, "SP", "B", "Optional dependencies", "Required dependencies clear", "Hidden dependencies", "Complex setup", "Constructor injection benefit?" },
                    { 24, "SP", "B", "Required properties", "Optional dependencies", "Always use it", "Never use it", "Property injection use case?" },
                    { 25, "SP", "B", "Permanent objects", "Temporary method usage", "Rare cases", "Always prefer it", "Method injection for?" },
                    { 26, "SP", "B", "Same thing", "DI preferred for testability", "Service Locator better", "Both identical", "Service Locator vs DI?" },
                    { 27, "SP", "B", "All equally", "Depends on context", "SRP", "DIP", "Which SOLID principle most important?" },
                    { 28, "SP", "B", "Unrelated", "Patterns implement SOLID", "SOLID requires patterns", "Opposite concepts", "SOLID and Design Patterns?" },
                    { 29, "SP", "B", "Rewrite completely", "Incremental improvement", "Not recommended", "Skip unnecessary", "Refactoring to SOLID?" },
                    { 30, "SP", "B", "No relationship", "SOLID improves testability", "SOLID makes testing harder", "Testing unrelated", "Testing and SOLID?" },
                    { 31, "SP", "B", "Different concepts", "Related concepts", "Opposite", "Unrelated", "SRP and cohesion?" },
                    { 32, "SP", "B", "No connection", "Abstraction enables OCP", "OCP enables abstraction", "Separate concerns", "OCP and abstraction?" },
                    { 33, "SP", "B", "No relationship", "LSP ensures type safety", "Type systems ignore LSP", "Unrelated fields", "LSP and type systems?" },
                    { 34, "SP", "B", "Increases coupling", "Reduces coupling", "No effect", "Random effect", "ISP and coupling?" },
                    { 35, "SP", "B", "Increases coupling", "Enables decoupling", "No effect", "Harmful", "DIP and decoupling?" },
                    { 36, "SP", "B", "Ignore SOLID", "Gradually apply SOLID", "Rewrite everything", "Can't apply SOLID", "Legacy code and SOLID?" },
                    { 37, "SP", "B", "Unrelated", "SOLID applies", "Prevents microservices", "Optional", "Microservices and SOLID?" },
                    { 38, "SP", "B", "Ignored", "Built-in support", "Discouraged", "Impossible", "SOLID in frameworks?" },
                    { 39, "SP", "B", "Never", "Complex legacy systems", "Simple scripts", "Performance critical", "When to relax SOLID?" },
                    { 40, "SP", "B", "SOLID ensures performance", "Trade-offs possible", "SOLID hurts performance", "No relationship", "SOLID and performance?" },
                    { 41, "SP", "B", "Apply everywhere", "Context-dependent", "Never apply", "Always necessary", "Over-engineering with SOLID?" },
                    { 42, "SP", "B", "Add more methods", "Customer/OrderRepository separation", "Merge classes", "Complex hierarchy", "Real-world SOLID example?" },
                    { 43, "SP", "B", "Unrelated", "SOLID supports agility", "SOLID prevents change", "Opposite concepts", "SOLID and agile?" },
                    { 44, "SP", "B", "Ignore it", "Key review points", "Optional", "Advanced only", "SOLID in code review?" },
                    { 45, "SP", "C", "3", "4", "5", "6", "SOLID principles count?" },
                    { 46, "SP", "B", "All at once", "Start with SRP, progress to DIP", "Random order", "Skip difficult ones", "Best SOLID learning path?" },
                    { 47, "SP", "B", "Nothing", "Increased maintenance", "Improves code", "No impact", "SOLID violations cost?" },
                    { 48, "SP", "B", "Requires rewrite", "SOLID handles change better", "No difference", "Makes it worse", "SOLID and requirements change?" },
                    { 49, "SP", "B", "MVC Controller", "God Class", "Repository", "Entity", "Which violates SRP most?" },
                    { 50, "SP", "B", "Not supported", "Dependency Injection container", "Manual wiring", "Not recommended", "DIP in ASP.NET Core?" },
                    { 51, "SP", "B", "Not needed", "Essential for understanding", "Burdens", "Wastes time", "SOLID documentation?" },
                    { 52, "SP", "B", "Individual concern", "Improves collaboration", "Creates conflict", "Irrelevant", "SOLID for teams?" },
                    { 53, "SP", "B", "Restrict framework", "Work with framework design", "Contradict framework", "Incompatible", "SOLID and frameworks?" },
                    { 54, "SP", "B", "Beginner skill", "Advanced skill", "Intermediate", "Expert only", "SOLID maturity level?" },
                    { 55, "SP", "B", "No benefit", "Long-term code quality", "Short-term cost", "Wastes money", "SOLID ROI?" },
                    { 56, "SP", "B", "Harder to test", "Easier to test", "No difference", "Impossible", "Testing SOLID code?" },
                    { 57, "SP", "B", "Never asked", "Common topic", "Rarely discussed", "Advanced only", "SOLID in interviews?" },
                    { 58, "SP", "B", "Useful?", "Demonstrates knowledge", "Not valuable", "Required", "SOLID certification?" },
                    { 59, "OOP", "B", "Inheritance", "Encapsulation", "Polymorphism", "Abstraction", "Which principle focuses on bundling data and methods?" },
                    { 60, "OOP", "B", "Same method name, different signatures", "Redefining parent method in child", "Changing method return type", "Creating multiple methods", "What is method overriding?" },
                    { 61, "OOP", "C", "abstract", "static", "sealed", "readonly", "Which keyword prevents inheritance?" },
                    { 62, "OOP", "B", "Multiple data types", "Same interface, different behavior", "Data hiding", "Code reusability", "What is polymorphism?" },
                    { 63, "OOP", "C", "protected", "public", "private", "internal", "Access modifier for same class only?" },
                    { 64, "OOP", "B", "Creating instances", "Hiding complexity", "Binding data", "Inheriting classes", "What is abstraction?" },
                    { 65, "OOP", "B", "Method hiding", "IS-A relationship", "HAS-A relationship", "Association", "Inheritance is also called?" },
                    { 66, "OOP", "B", "Classes", "Interfaces", "Structs", "Records", "Multiple inheritance in C# through?" },
                    { 67, "OOP", "A", "Late binding", "Early binding", "Static binding", "Compile-time binding", "Virtual keyword enables?" },
                    { 68, "OOP", "C", "Current class only", "Same assembly", "Derived classes", "All classes", "Protected modifier access level?" },
                    { 69, "OOP", "A", "HAS-A relationship", "IS-A relationship", "Polymorphism", "Abstraction", "What is composition?" },
                    { 70, "OOP", "B", "Only abstract members", "Constructor and abstract members", "No members", "Only static members", "Abstract class can have?" },
                    { 71, "OOP", "C", "Private methods", "Implementation", "Contracts/signatures", "Fields", "Interface can contain?" },
                    { 72, "OOP", "B", "Security", "Contract enforcement", "Performance", "Memory management", "Why use interfaces?" },
                    { 73, "OOP", "A", "Current class", "Base class", "Derived class", "Object reference", "this keyword refers to?" },
                    { 74, "OOP", "A", "Access parent members", "Access current class", "Create instance", "Initialize array", "base keyword used for?" },
                    { 75, "OOP", "B", "Instance", "Class", "Method", "Property", "Static member belongs to?" },
                    { 76, "OOP", "C", "Be inherited", "Have methods", "Not be inherited", "Be abstract", "Sealed class can?" },
                    { 77, "OOP", "C", "Polymorphism", "Multiple object creation", "Flexibility in initialization", "Memory optimization", "Constructor overloading achieves?" },
                    { 78, "OOP", "B", "Manually", "When object is garbage collected", "At compile time", "When method ends", "Destructor is called?" },
                    { 79, "OOP", "A", "Encapsulation", "Abstraction", "Inheritance", "Polymorphism", "Property with get/set is?" },
                    { 80, "OOP", "A", "Loose coupling", "Tight coupling", "Performance", "Memory efficiency", "Dependency Injection provides?" },
                    { 81, "OOP", "B", "Changeable", "Unchangeable", "Runtime only", "Thread-safe only", "const member is?" },
                    { 82, "OOP", "B", "Same thing", "readonly changeable in constructor", "readonly is static", "const is runtime", "readonly differs from const?" },
                    { 83, "OOP", "B", "Every object creation", "Once before any instance", "Never", "When garbage collected", "Static constructor runs?" },
                    { 84, "OOP", "B", "Classes only", "Existing types without inheritance", "Namespaces", "Assemblies", "Extension methods extend?" },
                    { 85, "OOP", "A", "Type safety", "Code duplication", "Performance loss", "Memory overhead", "Generic class provides?" },
                    { 86, "OOP", "B", "No relationship", "Covariance and Contravariance", "Only inheritance", "Method overloading", "Variance in generics?" },
                    { 87, "OOP", "B", "Variable scope", "Organization and avoiding name conflicts", "Memory management", "Compilation speed", "Namespace provides?" },
                    { 88, "OOP", "B", "Class only", "Same assembly", "Everywhere", "Only properties", "Internal modifier scope?" },
                    { 89, "OOP", "B", "Protected AND internal", "Protected OR internal", "Only protected", "Only internal", "Protected internal combines?" },
                    { 90, "OOP", "B", "Definition in one file", "Definition across multiple files", "Interface only", "Enum only", "Partial class allows?" },
                    { 91, "OOP", "A", "Temporary unnamed objects", "Permanent objects", "Only methods", "Only properties", "Anonymous type used for?" },
                    { 92, "OOP", "A", "SQL", "C++", "Java", "JavaScript", "LINQ query syntax resembles?" },
                    { 93, "OOP", "A", "Type-safe function pointers", "Classes", "Structs", "Properties", "Delegates are?" },
                    { 94, "OOP", "B", "Delegates", "Wrapper around delegates", "Methods", "Properties", "Events are?" },
                    { 95, "OOP", "B", "=>(parameters)=>body", "(parameters)=>body", "body=>parameters", "parameters==body", "Lambda expression syntax?" },
                    { 96, "OOP", "A", "Void", "Generic type", "String", "Int", "Action delegate returns?" },
                    { 97, "OOP", "B", "Void", "Specified type", "Always int", "Always string", "Func delegate returns?" },
                    { 98, "OOP", "A", "Func returning bool", "Action returning bool", "Delegate type", "Method only", "Predicate is?" },
                    { 99, "OOP", "A", "For iteration", "For storage", "For inheritance", "For static members", "IEnumerable is?" },
                    { 100, "OOP", "B", "Deferred execution locally", "Deferred execution on source", "Immediate execution", "No execution", "IQueryable is?" },
                    { 101, "OOP", "B", "Runtime code", "Lambda as tree", "Compilation", "Type info", "Expression tree represents?" },
                    { 102, "OOP", "B", "Always dynamic", "Compile-time inferred", "Runtime determined", "System.Object", "var keyword type?" },
                    { 103, "OOP", "B", "Compile-time", "Runtime", "Never", "Partially", "dynamic type checking?" },
                    { 104, "OOP", "B", "Non-nullable", "Optional values", "Always null", "Never null", "Nullable<T> usage?" },
                    { 105, "OOP", "C", "Comparison", "Null coalescing", "Safe navigation", "Casting", "?. operator effect?" },
                    { 106, "OOP", "A", "Right if left null", "Left if not null", "Both", "Result", "?? operator returns?" },
                    { 107, "OOP", "A", "Assignment if null", "Always assign", "Never assign", "Compare", "??= operator does?" },
                    { 108, "OOP", "B", "Optional", "Finally always runs", "Finally optional", "Catch always", "Try-catch-finally order?" },
                    { 109, "OOP", "A", "Resource management", "Namespace only", "Type safety", "Memory", "Using statement provides?" },
                    { 110, "OOP", "B", "Class only", "Multiple targets", "Method only", "Property only", "Attribute targets can?" },
                    { 111, "OOP", "B", "Compiled code", "Metadata", "Memory", "CPU", "Reflection accesses?" },
                    { 112, "OOP", "A", "Method object", "Integer", "String", "Type", "MethodInfo represents?" },
                    { 113, "OOP", "A", "Reading metadata", "Getting values", "Setting values", "Both get&set", "PropertyInfo allows?" },
                    { 114, "OOP", "A", "Creates type instance", "Deletes type", "Modifies type", "Lists types", "Activator.CreateInstance?" },
                    { 115, "DS", "B", "Queue", "Stack", "Heap", "Tree", "LIFO principle followed by?" },
                    { 116, "DS", "B", "Stack", "Queue", "Both", "Neither", "FIFO principle followed by?" },
                    { 117, "DS", "C", "O(n)", "O(log n)", "O(1)", "O(n^2)", "Array access time complexity?" },
                    { 118, "DS", "B", "O(1)", "O(n)", "O(log n)", "O(n^2)", "Array insertion worst case?" },
                    { 119, "DS", "B", "O(1)", "O(n)", "O(log n)", "O(n^2)", "Linked list access time?" },
                    { 120, "DS", "A", "O(1)", "O(n)", "O(log n)", "O(n^2)", "Linked list insertion at start?" },
                    { 121, "DS", "B", "Less memory", "Reverse traversal", "Faster", "Easier coding", "Doubly linked list advantage?" },
                    { 122, "DS", "C", "Simulation", "Undo/Redo", "Round-robin scheduling", "Linear search", "Circular linked list usage?" },
                    { 123, "DS", "B", "FIFO operations", "LIFO operations", "Sorting", "Searching", "Stack used for?" },
                    { 124, "DS", "A", "BFS graph traversal", "DFS graph traversal", "Stack simulation", "Recursion", "Queue used for?" },
                    { 125, "DS", "C", "Array", "Linked list", "Binary Heap", "AVL Tree", "Priority Queue uses?" },
                    { 126, "DS", "A", "Chaining and Open addressing", "Only chaining", "Only open addressing", "No solution", "Hash table collision?" },
                    { 127, "DS", "A", "Distribute uniformly", "Create clusters", "Hash same values", "Be slow", "Hash function should?" },
                    { 128, "DS", "B", "Left > Right", "Left < Right", "No order", "Random order", "Binary Search Tree property?" },
                    { 129, "DS", "B", "O(n)", "O(log n) average", "O(1)", "O(n^2)", "BST search time?" },
                    { 130, "DS", "A", "Balanced", "Unbalanced", "No height limit", "Only left heavy", "AVL tree ensures?" },
                    { 131, "DS", "B", "Balanced", "Semi-balanced", "Unbalanced", "Random color", "Red-Black tree property?" },
                    { 132, "DS", "B", "Parent >= children min-heap", "Parent <= children min-heap", "No order", "Random", "Binary heap property?" },
                    { 133, "DS", "B", "Maximum element", "Minimum element", "Middle element", "Random", "Min-heap root is?" },
                    { 134, "DS", "C", "O(n)", "O(log n)", "O(n log n)", "O(n^2)", "Heap sort time complexity?" },
                    { 135, "DS", "C", "Tree", "Array", "Adjacency matrix/list", "Stack", "Graph represented as?" },
                    { 136, "DS", "C", "Bidirectional", "Unidirectional", "Both possible", "No edges", "Directed graph edge?" },
                    { 137, "DS", "A", "Cost/weight", "Direction only", "Color", "Label only", "Weighted graph edge has?" },
                    { 138, "DS", "B", "Stack", "Queue", "Heap", "Tree", "BFS traversal uses?" },
                    { 139, "DS", "B", "Queue", "Stack", "Heap", "Deque", "DFS traversal uses?" },
                    { 140, "DS", "B", "Cyclic graphs", "DAGs", "Undirected graphs", "Binary trees", "Topological sort for?" },
                    { 141, "DS", "A", "Shortest path", "Longest path", "All paths", "Cycles", "Dijkstra finds?" },
                    { 142, "DS", "B", "Positive weights only", "Negative weights", "Cycles", "Disconnected graphs", "Bellman-Ford handles?" },
                    { 143, "DS", "B", "Single pair path", "All pairs path", "Shortest cycle", "Longest path", "Floyd-Warshall finds?" },
                    { 144, "DS", "B", "n+1 edges", "n-1 edges", "n edges", "2n edges", "Spanning tree has?" },
                    { 145, "DS", "B", "Dijkstra", "Kruskal/Prim", "DFS", "BFS", "MST can be found by?" },
                    { 146, "DS", "A", "Weight", "Vertex", "Color", "Index", "Kruskal sorts edges by?" },
                    { 147, "DS", "A", "Prefix searches", "Range searches", "Sorting", "Hashing", "Trie used for?" },
                    { 148, "DS", "A", "Databases", "Memory", "Cache", "Registers", "B-tree used in?" },
                    { 149, "DS", "A", "Range queries", "Single queries", "Sorting", "Searching", "Segment tree for?" },
                    { 150, "DS", "B", "O(n)", "O(log n)", "O(n^2)", "O(1)", "Fenwick tree time?" },
                    { 151, "DS", "A", "Random", "Fixed", "Deterministic", "None", "Skip list level?" },
                    { 152, "DS", "A", "Graph connectivity", "Sorting", "Searching", "Hashing", "Disjoint set union for?" },
                    { 153, "DS", "A", "Time complexity", "Space", "Comparison", "Swaps", "Union by rank optimizes?" },
                    { 154, "DS", "B", "Increases height", "Decreases height", "No effect", "Changes structure", "Path compression in DSU?" },
                    { 155, "DS", "B", "Skewed tree", "AVL tree", "Random tree", "Linear tree", "Tree height O(1) with?" },
                    { 156, "DS", "A", "String matching", "Number sorting", "Graph traversal", "Tree balancing", "Suffix array used for?" },
                    { 157, "DS", "C", "LPS array", "Failure array", "Both", "None", "KMP preprocessing creates?" },
                    { 158, "DS", "B", "Single character", "Multiple characters", "All characters", "No skipping", "Boyer-Moore skips?" },
                    { 159, "DS", "A", "Rolling hash", "Perfect hash", "No hash", "Static hash", "Rabin-Karp uses?" },
                    { 160, "DS", "B", "Time vs Space", "Memory vs Accuracy", "Speed vs Accuracy", "Space vs Time", "Bloom filter trade-off?" },
                    { 161, "DS", "A", "L1 > L2 > L3 > RAM", "RAM > L3 > L2 > L1", "L3 > L2 > L1 > RAM", "Equal speed", "Cache memory hierarchy?" },
                    { 162, "DS", "C", "Increase RAM", "Speed optimization", "Extend addressable space", "Reduce latency", "Virtual memory purpose?" },
                    { 163, "DS", "A", "Least Recently Used", "Least Relevant Used", "Long Running Units", "Local Regular Use", "Page replacement LRU?" },
                    { 164, "DS", "B", "Random size", "Power of 2 sizes", "Sequential", "Fragmented", "Buddy system allocates?" },
                    { 165, "DS", "C", "Internal only", "External only", "Both internal and external", "None", "Memory fragmentation type?" },
                    { 166, "DS", "A", "Redundancy", "Size fixed", "Complexity", "Speed", "Compression reduce by?" },
                    { 167, "DS", "A", "Dictionary", "Huffman", "RLE", "Arithmetic", "LZ77 compression uses?" },
                    { 168, "DS", "A", "Front and rear both", "Front only", "Rear only", "Random", "Deque operations?" },
                    { 169, "DS", "B", "Same thing", "Priority ordered differently", "No difference", "Always ordered", "Priority vs Regular Queue?" },
                    { 170, "DS", "A", "Boolean arrays", "Numbers only", "Strings", "Trees", "Bitset used for?" },
                    { 171, "DS", "B", "Garden tool", "Heavy string operations", "Integers", "Sorting", "Rope data structure?" },
                    { 172, ".NET", "A", "Common Language Runtime", "Code Level Reuse", "C# Library Runtime", "Common Logic Run", "CLR stands for?" },
                    { 173, ".NET", "B", "Optional", "For language interop", "Only C#", "Never needed", "CLS requirement?" },
                    { 174, ".NET", "B", "Direct CPU", "JIT compiler", "Interpreter", "Native code", "IL code executes via?" },
                    { 175, ".NET", "B", "Manual memory", "GC and safety", "Faster execution", "Lower level", "Managed code benefits?" },
                    { 176, ".NET", "A", "2002", "2005", "1999", "2000", ".NET Framework release?" },
                    { 177, ".NET", "B", "Windows only", "Cross-platform", "Enterprise", "Web only", ".NET Core purpose?" },
                    { 178, ".NET", "B", "Framework only", "Core + Framework", "Separate", "Beta", ".NET 5 unification?" },
                    { 179, ".NET", "A", "Task", "Promise", "Future", "Coroutine", "async/await returns?" },
                    { 180, ".NET", "B", "Synchronous work", "Asynchronous work", "Cancelled operation", "Failed task", "Task<T> represents?" },
                    { 181, ".NET", "B", "Blocks thread", "Async wait", "Throws exception", "Returns null", "await keyword does?" },
                    { 182, ".NET", "A", "Events only", "Always ok", "Never use", "Methods only", "async void usage?" },
                    { 183, ".NET", "B", "C# 5", "C# 7.1+", "C# 8", "Never", "async Main support?" },
                    { 184, ".NET", "C", "Interface", "Function pointer", "Method signature", "Class", "Delegate syntax?" },
                    { 185, ".NET", "C", "Encapsulation", "No access", "Controllable invocation", "Data hiding", "Event modifier ensures?" },
                    { 186, ".NET", "B", "Verbose", "Concise syntax", "Always faster", "Type safe only", "Lambda expression benefit?" },
                    { 187, ".NET", "B", "void Method(int)", "int Add(int,int)", "public void Go()", "no return", "Func<T1,TResult> example?" },
                    { 188, ".NET", "B", "Generic T", "Void", "Bool", "Int", "Action<T> returns?" },
                    { 189, ".NET", "B", "All types", "bool return", "void only", "int only", "Predicate<T> uses?" },
                    { 190, ".NET", "B", "Immediate", "Until enumeration", "At declaration", "At definition", "LINQ deferred execution?" },
                    { 191, ".NET", "B", "Same thing", "Queryable for data sources", "IEnumerable faster", "No difference", "IEnumerable vs IQueryable?" },
                    { 192, ".NET", "B", "Runtime code", "Lambda as tree", "Compilation", "Type info", "Expression tree represents?" },
                    { 193, ".NET", "B", "Always dynamic", "Compile-time inferred", "Runtime determined", "System.Object", "var keyword type?" },
                    { 194, ".NET", "B", "Compile-time", "Runtime", "Never", "Partially", "dynamic type checking?" },
                    { 195, ".NET", "B", "Normal", "this keyword", "ref", "params", "Extension method first param?" },
                    { 196, ".NET", "B", "Non-nullable", "Optional values", "Always null", "Never null", "Nullable<T> usage?" },
                    { 197, ".NET", "C", "Comparison", "Null coalescing", "Safe navigation", "Casting", "?. operator effect?" },
                    { 198, ".NET", "A", "Right if left null", "Left if not null", "Both", "Result", "?? operator returns?" },
                    { 199, ".NET", "A", "Assignment if null", "Always assign", "Never assign", "Compare", "??= operator does?" },
                    { 200, ".NET", "B", "Optional", "Finally always runs", "Finally optional", "Catch always", "Try-catch-finally order?" },
                    { 201, ".NET", "A", "Resource management", "Namespace only", "Type safety", "Memory", "Using statement provides?" },
                    { 202, ".NET", "B", "Class only", "Multiple targets", "Method only", "Property only", "Attribute targets can?" },
                    { 203, ".NET", "B", "Compiled code", "Metadata", "Memory", "CPU", "Reflection accesses?" },
                    { 204, ".NET", "A", "Method object", "Integer", "String", "Type", "MethodInfo represents?" },
                    { 205, ".NET", "A", "Reading metadata", "Getting values", "Setting values", "Both get&set", "PropertyInfo allows?" },
                    { 206, ".NET", "A", "Creates type instance", "Deletes type", "Modifies type", "Lists types", "Activator.CreateInstance?" },
                    { 207, ".NET", "B", "Entity Framework", "EF and LINQ", "Only classes", "No benefits", "POCO benefits?" },
                    { 208, ".NET", "B", "Database table", "ORM session", "SQL connection", "DbSet", "DbContext represents?" },
                    { 209, ".NET", "B", "Single record", "Table/collection", "Database", "Query", "DbSet<T> represents?" },
                    { 210, ".NET", "A", "All entities", "New entities", "Deleted entities", "All changes", "SaveChanges tracks?" },
                    { 211, ".NET", "A", "Include()", "First()", "Where()", "Select()", "Eager loading uses?" },
                    { 212, ".NET", "C", "Always on", "Off in some contexts", "Virtual navigation", "Disabled", "Lazy loading default?" },
                    { 213, ".NET", "C", "Load()", "Load<T>()", "Entry().Collection()", "Correct answers", "Explicit loading uses?" },
                    { 214, ".NET", "B", "Foreign key", "Related entity", "Data column", "Table name", "Navigation property?" },
                    { 215, ".NET", "B", "Database only", "Hidden from model", "Type safety", "Performance", "Shadow property purpose?" },
                    { 216, ".NET", "B", "Has ID", "No ID", "Table mapped", "Always persisted", "Value object in EF?" },
                    { 217, ".NET", "B", "Separate table", "Parent table", "No mapping", "Optional", "Owned entity mapping?" },
                    { 218, ".NET", "A", "Primary key", "Foreign key", "Index", "Constraint", "HasKey() designates?" },
                    { 219, ".NET", "A", "One to many", "Many to one", "Many to many", "One to one", "HasMany().WithOne?" },
                    { 220, ".NET", "B", "Many to many", "One to many", "One to one", "Many to one", "HasOne().WithMany?" },
                    { 221, ".NET", "C", "One to one", "One to many", "Many to many", "Tree", "HasMany().WithMany?" },
                    { 222, ".NET", "B", "No version", "Auto incrementing", "Timestamp", "Manual", "Migration adds version?" },
                    { 223, ".NET", "A", "Migration file", "Database", "Table", "Connection", "Add-Migration creates?" },
                    { 224, ".NET", "B", "EF model", "Pending migrations", "Current migration", "All migrations", "Update-Database applies?" },
                    { 225, ".NET", "C", "DbContext", "Models from DB", "Both context and models", "Migrations", "Scaffold-DbContext generates?" },
                    { 226, ".NET", "A", "Stored", "Not stored", "Always computed", "Never used", "Computed columns in DB?" },
                    { 227, ".NET", "B", "Duplicate keys", "Simultaneous updates", "Null values", "Invalid types", "Concurrency token prevents?" },
                    { 228, ".NET", "D", "None", "Data Annotations", "Fluent API", "Both", "Model validation in EF?" },
                    { 229, ".NET", "A", "Once per context", "Every operation", "Never", "Rarely", "OnModelCreating called?" },
                    { 230, ".NET", "D", "Soft delete", "Multi-tenancy", "Security", "All above", "GlobalQueryFilters for?" }
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Questions");

            migrationBuilder.DropTable(
                name: "Winners");
        }
    }
}
